//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace ConTech.Data.Read.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'ProjectView'.</summary>
	[Serializable]
	[DataContract]
	public partial class ProjectViewLlblView
	{
		/// <summary>Gets or sets the BackgroundPdf field. Derived from Entity Model Field 'ProjectView.BackgroundPdf'</summary>
		[DataMember]
		public System.Byte[] BackgroundPdf { get; set; }
		/// <summary>Gets or sets the CreatedByUserId field. Derived from Entity Model Field 'ProjectView.CreatedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> CreatedByUserId { get; set; }
		/// <summary>Gets or sets the DateCreatedUtc field. Derived from Entity Model Field 'ProjectView.DateCreatedUtc'</summary>
		[DataMember]
		public System.DateTime DateCreatedUtc { get; set; }
		/// <summary>Gets or sets the Description field. Derived from Entity Model Field 'ProjectView.Description'</summary>
		[DataMember]
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'ProjectView.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the LastModifiedByUserId field. Derived from Entity Model Field 'ProjectView.LastModifiedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> LastModifiedByUserId { get; set; }
		/// <summary>Gets or sets the LastModifiedUtc field. Derived from Entity Model Field 'ProjectView.LastModifiedUtc'</summary>
		[DataMember]
		public Nullable<System.DateTime> LastModifiedUtc { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'ProjectView.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the ObjectStatus field. Derived from Entity Model Field 'ProjectView.ObjectStatus'</summary>
		[DataMember]
		public System.Int32 ObjectStatus { get; set; }
		/// <summary>Gets or sets the ProjectId field. Derived from Entity Model Field 'ProjectView.ProjectId (FK)'</summary>
		[DataMember]
		public System.Int32 ProjectId { get; set; }
	}

}




