//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ConTech.Data.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitEntityTypeEntityMappings();
			InitLevelChildEntityMappings();
			InitLevelEntityEntityMappings();
			InitPersonEntityMappings();
			InitProjectEntityMappings();
			InitProjectViewEntityMappings();
			InitUserEntityMappings();
			InitViewLevelEntityMappings();
		}

		/// <summary>Inits EntityTypeEntity's mappings</summary>
		private void InitEntityTypeEntityMappings()
		{
			this.AddElementMapping("EntityTypeEntity", @"ConTech", @"dbo", "EntityType", 8, 0);
			this.AddElementFieldMapping("EntityTypeEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("EntityTypeEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("EntityTypeEntity", "Id", "Id", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("EntityTypeEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("EntityTypeEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("EntityTypeEntity", "NameArabic", "NameArabic", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("EntityTypeEntity", "NameEnglish", "NameEnglish", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("EntityTypeEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
		}

		/// <summary>Inits LevelChildEntity's mappings</summary>
		private void InitLevelChildEntityMappings()
		{
			this.AddElementMapping("LevelChildEntity", @"ConTech", @"dbo", "LevelChild", 11, 0);
			this.AddElementFieldMapping("LevelChildEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("LevelChildEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("LevelChildEntity", "Description", "Description", true, "NVarChar", 750, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("LevelChildEntity", "EntityList", "EntityList", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("LevelChildEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("LevelChildEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("LevelChildEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("LevelChildEntity", "LevelId", "LevelId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 7);
			this.AddElementFieldMapping("LevelChildEntity", "Name", "Name", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("LevelChildEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 9);
			this.AddElementFieldMapping("LevelChildEntity", "ParentId", "ParentId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 10);
		}

		/// <summary>Inits LevelEntityEntity's mappings</summary>
		private void InitLevelEntityEntityMappings()
		{
			this.AddElementMapping("LevelEntityEntity", @"ConTech", @"dbo", "LevelEntity", 15, 0);
			this.AddElementFieldMapping("LevelEntityEntity", "ColorCode", "ColorCode", true, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("LevelEntityEntity", "ColorIndex", "ColorIndex", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("LevelEntityEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("LevelEntityEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("LevelEntityEntity", "EntityName", "EntityName", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("LevelEntityEntity", "EntityTypeId", "EntityTypeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("LevelEntityEntity", "Frozen", "Frozen", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 6);
			this.AddElementFieldMapping("LevelEntityEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 7);
			this.AddElementFieldMapping("LevelEntityEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("LevelEntityEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 9);
			this.AddElementFieldMapping("LevelEntityEntity", "LevelId", "LevelId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 10);
			this.AddElementFieldMapping("LevelEntityEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 11);
			this.AddElementFieldMapping("LevelEntityEntity", "UniqueId", "UniqueId", true, "NVarChar", 750, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("LevelEntityEntity", "Vertices", "Vertices", true, "NVarChar", 1000, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("LevelEntityEntity", "Visible", "Visible", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 14);
		}

		/// <summary>Inits PersonEntity's mappings</summary>
		private void InitPersonEntityMappings()
		{
			this.AddElementMapping("PersonEntity", @"ConTech", @"dbo", "Person", 13, 0);
			this.AddElementFieldMapping("PersonEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PersonEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("PersonEntity", "Email", "Email", true, "NVarChar", 500, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("PersonEntity", "FirstName", "FirstName", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("PersonEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("PersonEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("PersonEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("PersonEntity", "LastName", "LastName", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("PersonEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("PersonEntity", "Phone", "Phone", true, "NVarChar", 40, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("PersonEntity", "Title", "Title", true, "NVarChar", 40, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("PersonEntity", "VerificationCode", "VerificationCode", true, "NVarChar", 4, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("PersonEntity", "Verified", "Verified", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 12);
		}

		/// <summary>Inits ProjectEntity's mappings</summary>
		private void InitProjectEntityMappings()
		{
			this.AddElementMapping("ProjectEntity", @"ConTech", @"dbo", "Project", 8, 0);
			this.AddElementFieldMapping("ProjectEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("ProjectEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("ProjectEntity", "Description", "Description", true, "NVarChar", 750, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("ProjectEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("ProjectEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("ProjectEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("ProjectEntity", "Name", "Name", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("ProjectEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
		}

		/// <summary>Inits ProjectViewEntity's mappings</summary>
		private void InitProjectViewEntityMappings()
		{
			this.AddElementMapping("ProjectViewEntity", @"ConTech", @"dbo", "ProjectView", 10, 0);
			this.AddElementFieldMapping("ProjectViewEntity", "BackgroundPdf", "BackgroundPdf", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("ProjectViewEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("ProjectViewEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("ProjectViewEntity", "Description", "Description", true, "NVarChar", 750, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ProjectViewEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("ProjectViewEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("ProjectViewEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("ProjectViewEntity", "Name", "Name", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("ProjectViewEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("ProjectViewEntity", "ProjectId", "ProjectId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 9);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"ConTech", @"dbo", "User", 10, 0);
			this.AddElementFieldMapping("UserEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UserEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("UserEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("UserEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("UserEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("UserEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 5);
			this.AddElementFieldMapping("UserEntity", "Password", "Password", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("UserEntity", "PersonId", "PersonId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
			this.AddElementFieldMapping("UserEntity", "ResetExpirationDate", "ResetExpirationDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 8);
			this.AddElementFieldMapping("UserEntity", "ResetToken", "ResetToken", true, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 9);
		}

		/// <summary>Inits ViewLevelEntity's mappings</summary>
		private void InitViewLevelEntityMappings()
		{
			this.AddElementMapping("ViewLevelEntity", @"ConTech", @"dbo", "ViewLevel", 14, 0);
			this.AddElementFieldMapping("ViewLevelEntity", "CreatedByUserId", "CreatedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("ViewLevelEntity", "DateCreatedUtc", "DateCreatedUtc", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("ViewLevelEntity", "Description", "Description", true, "NVarChar", 750, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("ViewLevelEntity", "DxfData", "DxfData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ViewLevelEntity", "EntityData", "EntityData", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("ViewLevelEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
			this.AddElementFieldMapping("ViewLevelEntity", "LastModifiedByUserId", "LastModifiedByUserId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 6);
			this.AddElementFieldMapping("ViewLevelEntity", "LastModifiedUtc", "LastModifiedUtc", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
			this.AddElementFieldMapping("ViewLevelEntity", "Name", "Name", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("ViewLevelEntity", "ObjectStatus", "ObjectStatus", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 9);
			this.AddElementFieldMapping("ViewLevelEntity", "Scale", "Scale", true, "Real", 0, 24, 0, false, "", null, typeof(System.Single), 10);
			this.AddElementFieldMapping("ViewLevelEntity", "TransitionX", "TransitionX", true, "Real", 0, 24, 0, false, "", null, typeof(System.Single), 11);
			this.AddElementFieldMapping("ViewLevelEntity", "TransitionY", "TransitionY", true, "Real", 0, 24, 0, false, "", null, typeof(System.Single), 12);
			this.AddElementFieldMapping("ViewLevelEntity", "ViewId", "ViewId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 13);
		}

	}
}
