//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace ConTech.Data
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>EntityType</summary>
		EntityTypeEntity,
		///<summary>LevelChild</summary>
		LevelChildEntity,
		///<summary>LevelEntity</summary>
		LevelEntityEntity,
		///<summary>Person</summary>
		PersonEntity,
		///<summary>Project</summary>
		ProjectEntity,
		///<summary>ProjectView</summary>
		ProjectViewEntity,
		///<summary>User</summary>
		UserEntity,
		///<summary>ViewLevel</summary>
		ViewLevelEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

