//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using ConTech.Data.EntityClasses;
using ConTech.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace ConTech.Data.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the EntityType entity</summary>
		public EntityQuery<EntityTypeEntity> EntityType { get { return Create<EntityTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the LevelChild entity</summary>
		public EntityQuery<LevelChildEntity> LevelChild { get { return Create<LevelChildEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the LevelEntity entity</summary>
		public EntityQuery<LevelEntityEntity> LevelEntity { get { return Create<LevelEntityEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Person entity</summary>
		public EntityQuery<PersonEntity> Person { get { return Create<PersonEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Project entity</summary>
		public EntityQuery<ProjectEntity> Project { get { return Create<ProjectEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProjectView entity</summary>
		public EntityQuery<ProjectViewEntity> ProjectView { get { return Create<ProjectViewEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ViewLevel entity</summary>
		public EntityQuery<ViewLevelEntity> ViewLevel { get { return Create<ViewLevelEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}