//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace ConTech.Data.Read.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Project'.</summary>
	[Serializable]
	[DataContract]
	public partial class ProjectView
	{
		/// <summary>Gets or sets the CreatedByUserId field. Derived from Entity Model Field 'Project.CreatedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> CreatedByUserId { get; set; }
		/// <summary>Gets or sets the DateCreatedUtc field. Derived from Entity Model Field 'Project.DateCreatedUtc'</summary>
		[DataMember]
		public System.DateTime DateCreatedUtc { get; set; }
		/// <summary>Gets or sets the Description field. Derived from Entity Model Field 'Project.Description'</summary>
		[DataMember]
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Project.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the LastModifiedByUserId field. Derived from Entity Model Field 'Project.LastModifiedByUserId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> LastModifiedByUserId { get; set; }
		/// <summary>Gets or sets the LastModifiedUtc field. Derived from Entity Model Field 'Project.LastModifiedUtc'</summary>
		[DataMember]
		public Nullable<System.DateTime> LastModifiedUtc { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Project.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the ObjectStatus field. Derived from Entity Model Field 'Project.ObjectStatus'</summary>
		[DataMember]
		public System.Int32 ObjectStatus { get; set; }
	}

}




