//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ConTech.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity EntityTypeEntity</summary>
	public partial class EntityTypeFields
	{
		/// <summary>Creates a new EntityTypeEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new EntityTypeEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new EntityTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.Id); }}
		/// <summary>Creates a new EntityTypeEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new EntityTypeEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new EntityTypeEntity.NameArabic field instance</summary>
		public static EntityField2 NameArabic { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.NameArabic); }}
		/// <summary>Creates a new EntityTypeEntity.NameEnglish field instance</summary>
		public static EntityField2 NameEnglish { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.NameEnglish); }}
		/// <summary>Creates a new EntityTypeEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EntityTypeFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity LevelChildEntity</summary>
	public partial class LevelChildFields
	{
		/// <summary>Creates a new LevelChildEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new LevelChildEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new LevelChildEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.Description); }}
		/// <summary>Creates a new LevelChildEntity.EntityList field instance</summary>
		public static EntityField2 EntityList { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.EntityList); }}
		/// <summary>Creates a new LevelChildEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.Id); }}
		/// <summary>Creates a new LevelChildEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new LevelChildEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new LevelChildEntity.LevelId field instance</summary>
		public static EntityField2 LevelId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.LevelId); }}
		/// <summary>Creates a new LevelChildEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.Name); }}
		/// <summary>Creates a new LevelChildEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new LevelChildEntity.ParentId field instance</summary>
		public static EntityField2 ParentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelChildFieldIndex.ParentId); }}
	}

	/// <summary>Field Creation Class for entity LevelEntityEntity</summary>
	public partial class LevelEntityFields
	{
		/// <summary>Creates a new LevelEntityEntity.ColorCode field instance</summary>
		public static EntityField2 ColorCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.ColorCode); }}
		/// <summary>Creates a new LevelEntityEntity.ColorIndex field instance</summary>
		public static EntityField2 ColorIndex { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.ColorIndex); }}
		/// <summary>Creates a new LevelEntityEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new LevelEntityEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new LevelEntityEntity.EntityName field instance</summary>
		public static EntityField2 EntityName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.EntityName); }}
		/// <summary>Creates a new LevelEntityEntity.EntityTypeId field instance</summary>
		public static EntityField2 EntityTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.EntityTypeId); }}
		/// <summary>Creates a new LevelEntityEntity.Frozen field instance</summary>
		public static EntityField2 Frozen { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.Frozen); }}
		/// <summary>Creates a new LevelEntityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.Id); }}
		/// <summary>Creates a new LevelEntityEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new LevelEntityEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new LevelEntityEntity.LevelId field instance</summary>
		public static EntityField2 LevelId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.LevelId); }}
		/// <summary>Creates a new LevelEntityEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new LevelEntityEntity.UniqueId field instance</summary>
		public static EntityField2 UniqueId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.UniqueId); }}
		/// <summary>Creates a new LevelEntityEntity.Vertices field instance</summary>
		public static EntityField2 Vertices { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.Vertices); }}
		/// <summary>Creates a new LevelEntityEntity.Visible field instance</summary>
		public static EntityField2 Visible { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LevelEntityFieldIndex.Visible); }}
	}

	/// <summary>Field Creation Class for entity PersonEntity</summary>
	public partial class PersonFields
	{
		/// <summary>Creates a new PersonEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new PersonEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new PersonEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Email); }}
		/// <summary>Creates a new PersonEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.FirstName); }}
		/// <summary>Creates a new PersonEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Id); }}
		/// <summary>Creates a new PersonEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new PersonEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new PersonEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.LastName); }}
		/// <summary>Creates a new PersonEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new PersonEntity.Phone field instance</summary>
		public static EntityField2 Phone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Phone); }}
		/// <summary>Creates a new PersonEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Title); }}
		/// <summary>Creates a new PersonEntity.VerificationCode field instance</summary>
		public static EntityField2 VerificationCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.VerificationCode); }}
		/// <summary>Creates a new PersonEntity.Verified field instance</summary>
		public static EntityField2 Verified { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PersonFieldIndex.Verified); }}
	}

	/// <summary>Field Creation Class for entity ProjectEntity</summary>
	public partial class ProjectFields
	{
		/// <summary>Creates a new ProjectEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new ProjectEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new ProjectEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Description); }}
		/// <summary>Creates a new ProjectEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Id); }}
		/// <summary>Creates a new ProjectEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new ProjectEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new ProjectEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Name); }}
		/// <summary>Creates a new ProjectEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.ObjectStatus); }}
	}

	/// <summary>Field Creation Class for entity ProjectViewEntity</summary>
	public partial class ProjectViewFields
	{
		/// <summary>Creates a new ProjectViewEntity.BackgroundPdf field instance</summary>
		public static EntityField2 BackgroundPdf { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.BackgroundPdf); }}
		/// <summary>Creates a new ProjectViewEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new ProjectViewEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new ProjectViewEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.Description); }}
		/// <summary>Creates a new ProjectViewEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.Id); }}
		/// <summary>Creates a new ProjectViewEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new ProjectViewEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new ProjectViewEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.Name); }}
		/// <summary>Creates a new ProjectViewEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new ProjectViewEntity.ProjectId field instance</summary>
		public static EntityField2 ProjectId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectViewFieldIndex.ProjectId); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new UserEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new UserEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new UserEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
		/// <summary>Creates a new UserEntity.PersonId field instance</summary>
		public static EntityField2 PersonId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PersonId); }}
		/// <summary>Creates a new UserEntity.ResetExpirationDate field instance</summary>
		public static EntityField2 ResetExpirationDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ResetExpirationDate); }}
		/// <summary>Creates a new UserEntity.ResetToken field instance</summary>
		public static EntityField2 ResetToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.ResetToken); }}
	}

	/// <summary>Field Creation Class for entity ViewLevelEntity</summary>
	public partial class ViewLevelFields
	{
		/// <summary>Creates a new ViewLevelEntity.CreatedByUserId field instance</summary>
		public static EntityField2 CreatedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.CreatedByUserId); }}
		/// <summary>Creates a new ViewLevelEntity.DateCreatedUtc field instance</summary>
		public static EntityField2 DateCreatedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.DateCreatedUtc); }}
		/// <summary>Creates a new ViewLevelEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.Description); }}
		/// <summary>Creates a new ViewLevelEntity.DxfData field instance</summary>
		public static EntityField2 DxfData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.DxfData); }}
		/// <summary>Creates a new ViewLevelEntity.DxfFile field instance</summary>
		public static EntityField2 DxfFile { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.DxfFile); }}
		/// <summary>Creates a new ViewLevelEntity.EntityData field instance</summary>
		public static EntityField2 EntityData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.EntityData); }}
		/// <summary>Creates a new ViewLevelEntity.ExcelFile field instance</summary>
		public static EntityField2 ExcelFile { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.ExcelFile); }}
		/// <summary>Creates a new ViewLevelEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.Id); }}
		/// <summary>Creates a new ViewLevelEntity.LastModifiedByUserId field instance</summary>
		public static EntityField2 LastModifiedByUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.LastModifiedByUserId); }}
		/// <summary>Creates a new ViewLevelEntity.LastModifiedUtc field instance</summary>
		public static EntityField2 LastModifiedUtc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.LastModifiedUtc); }}
		/// <summary>Creates a new ViewLevelEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.Name); }}
		/// <summary>Creates a new ViewLevelEntity.ObjectStatus field instance</summary>
		public static EntityField2 ObjectStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.ObjectStatus); }}
		/// <summary>Creates a new ViewLevelEntity.Scale field instance</summary>
		public static EntityField2 Scale { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.Scale); }}
		/// <summary>Creates a new ViewLevelEntity.TransitionX field instance</summary>
		public static EntityField2 TransitionX { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.TransitionX); }}
		/// <summary>Creates a new ViewLevelEntity.TransitionY field instance</summary>
		public static EntityField2 TransitionY { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.TransitionY); }}
		/// <summary>Creates a new ViewLevelEntity.ViewId field instance</summary>
		public static EntityField2 ViewId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewLevelFieldIndex.ViewId); }}
	}
	

}