//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using ConTech.Data.FactoryClasses;
using ConTech.Data.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ConTech.Data.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitEntityTypeEntityInfo();
			InitLevelChildEntityInfo();
			InitLevelEntityEntityInfo();
			InitPersonEntityInfo();
			InitProjectEntityInfo();
			InitProjectViewEntityInfo();
			InitUserEntityInfo();
			InitViewLevelEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits EntityTypeEntity's info objects</summary>
		private void InitEntityTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EntityTypeFieldIndex), "EntityTypeEntity");
			this.AddElementFieldInfo("EntityTypeEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)EntityTypeFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("EntityTypeEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)EntityTypeFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("EntityTypeEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)EntityTypeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("EntityTypeEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)EntityTypeFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("EntityTypeEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)EntityTypeFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("EntityTypeEntity", "NameArabic", typeof(System.String), false, false, false, false,  (int)EntityTypeFieldIndex.NameArabic, 200, 0, 0);
			this.AddElementFieldInfo("EntityTypeEntity", "NameEnglish", typeof(System.String), false, false, false, true,  (int)EntityTypeFieldIndex.NameEnglish, 200, 0, 0);
			this.AddElementFieldInfo("EntityTypeEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)EntityTypeFieldIndex.ObjectStatus, 0, 0, 10);
		}

		/// <summary>Inits LevelChildEntity's info objects</summary>
		private void InitLevelChildEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LevelChildFieldIndex), "LevelChildEntity");
			this.AddElementFieldInfo("LevelChildEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)LevelChildFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("LevelChildEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)LevelChildFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "Description", typeof(System.String), false, false, false, true,  (int)LevelChildFieldIndex.Description, 750, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "EntityList", typeof(System.String), false, false, false, true,  (int)LevelChildFieldIndex.EntityList, 2147483647, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)LevelChildFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)LevelChildFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("LevelChildEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)LevelChildFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "LevelId", typeof(System.Guid), false, true, false, false,  (int)LevelChildFieldIndex.LevelId, 0, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "Name", typeof(System.String), false, false, false, false,  (int)LevelChildFieldIndex.Name, 200, 0, 0);
			this.AddElementFieldInfo("LevelChildEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)LevelChildFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("LevelChildEntity", "ParentId", typeof(Nullable<System.Guid>), false, false, false, true,  (int)LevelChildFieldIndex.ParentId, 0, 0, 0);
		}

		/// <summary>Inits LevelEntityEntity's info objects</summary>
		private void InitLevelEntityEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LevelEntityFieldIndex), "LevelEntityEntity");
			this.AddElementFieldInfo("LevelEntityEntity", "ColorCode", typeof(System.String), false, false, false, true,  (int)LevelEntityFieldIndex.ColorCode, 20, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "ColorIndex", typeof(System.Int32), false, false, false, false,  (int)LevelEntityFieldIndex.ColorIndex, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)LevelEntityFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)LevelEntityFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "EntityName", typeof(System.String), false, false, false, false,  (int)LevelEntityFieldIndex.EntityName, 200, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "EntityTypeId", typeof(System.Int32), false, true, false, false,  (int)LevelEntityFieldIndex.EntityTypeId, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "Frozen", typeof(System.Boolean), false, false, false, false,  (int)LevelEntityFieldIndex.Frozen, 0, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)LevelEntityFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)LevelEntityFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)LevelEntityFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "LevelId", typeof(System.Guid), false, true, false, false,  (int)LevelEntityFieldIndex.LevelId, 0, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)LevelEntityFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("LevelEntityEntity", "UniqueId", typeof(System.String), false, false, false, true,  (int)LevelEntityFieldIndex.UniqueId, 750, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "Vertices", typeof(System.String), false, false, false, true,  (int)LevelEntityFieldIndex.Vertices, 1000, 0, 0);
			this.AddElementFieldInfo("LevelEntityEntity", "Visible", typeof(System.Boolean), false, false, false, false,  (int)LevelEntityFieldIndex.Visible, 0, 0, 0);
		}

		/// <summary>Inits PersonEntity's info objects</summary>
		private void InitPersonEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PersonFieldIndex), "PersonEntity");
			this.AddElementFieldInfo("PersonEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)PersonFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("PersonEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)PersonFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "Email", typeof(System.String), false, false, false, true,  (int)PersonFieldIndex.Email, 500, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)PersonFieldIndex.FirstName, 200, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)PersonFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("PersonEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)PersonFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("PersonEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)PersonFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "LastName", typeof(System.String), false, false, false, false,  (int)PersonFieldIndex.LastName, 200, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)PersonFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("PersonEntity", "Phone", typeof(System.String), false, false, false, true,  (int)PersonFieldIndex.Phone, 40, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "Title", typeof(System.String), false, false, false, true,  (int)PersonFieldIndex.Title, 40, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "VerificationCode", typeof(System.String), false, false, false, true,  (int)PersonFieldIndex.VerificationCode, 4, 0, 0);
			this.AddElementFieldInfo("PersonEntity", "Verified", typeof(System.Boolean), false, false, false, false,  (int)PersonFieldIndex.Verified, 0, 0, 0);
		}

		/// <summary>Inits ProjectEntity's info objects</summary>
		private void InitProjectEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProjectFieldIndex), "ProjectEntity");
			this.AddElementFieldInfo("ProjectEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ProjectFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ProjectEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)ProjectFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ProjectEntity", "Description", typeof(System.String), false, false, false, true,  (int)ProjectFieldIndex.Description, 750, 0, 0);
			this.AddElementFieldInfo("ProjectEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ProjectFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ProjectEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ProjectFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ProjectEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ProjectFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ProjectEntity", "Name", typeof(System.String), false, false, false, false,  (int)ProjectFieldIndex.Name, 200, 0, 0);
			this.AddElementFieldInfo("ProjectEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)ProjectFieldIndex.ObjectStatus, 0, 0, 10);
		}

		/// <summary>Inits ProjectViewEntity's info objects</summary>
		private void InitProjectViewEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ProjectViewFieldIndex), "ProjectViewEntity");
			this.AddElementFieldInfo("ProjectViewEntity", "BackgroundPdf", typeof(System.Byte[]), false, false, false, true,  (int)ProjectViewFieldIndex.BackgroundPdf, 2147483647, 0, 0);
			this.AddElementFieldInfo("ProjectViewEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ProjectViewFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ProjectViewEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)ProjectViewFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ProjectViewEntity", "Description", typeof(System.String), false, false, false, true,  (int)ProjectViewFieldIndex.Description, 750, 0, 0);
			this.AddElementFieldInfo("ProjectViewEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ProjectViewFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ProjectViewEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ProjectViewFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ProjectViewEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ProjectViewFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ProjectViewEntity", "Name", typeof(System.String), false, false, false, false,  (int)ProjectViewFieldIndex.Name, 200, 0, 0);
			this.AddElementFieldInfo("ProjectViewEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)ProjectViewFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("ProjectViewEntity", "ProjectId", typeof(System.Int32), false, true, false, false,  (int)ProjectViewFieldIndex.ProjectId, 0, 0, 10);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)UserFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)UserFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)UserFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "Password", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Password, 200, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PersonId", typeof(System.Int32), false, true, false, false,  (int)UserFieldIndex.PersonId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "ResetExpirationDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.ResetExpirationDate, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "ResetToken", typeof(Nullable<System.Guid>), false, false, false, true,  (int)UserFieldIndex.ResetToken, 0, 0, 0);
		}

		/// <summary>Inits ViewLevelEntity's info objects</summary>
		private void InitViewLevelEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ViewLevelFieldIndex), "ViewLevelEntity");
			this.AddElementFieldInfo("ViewLevelEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ViewLevelFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ViewLevelEntity", "DateCreatedUtc", typeof(System.DateTime), false, false, false, false,  (int)ViewLevelFieldIndex.DateCreatedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "Description", typeof(System.String), false, false, false, true,  (int)ViewLevelFieldIndex.Description, 750, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "DxfData", typeof(System.String), false, false, false, true,  (int)ViewLevelFieldIndex.DxfData, 2147483647, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "DxfFile", typeof(System.Byte[]), false, false, false, true,  (int)ViewLevelFieldIndex.DxfFile, 2147483647, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "EntityData", typeof(System.String), false, false, false, true,  (int)ViewLevelFieldIndex.EntityData, 2147483647, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "ExcelFile", typeof(System.Byte[]), false, false, false, true,  (int)ViewLevelFieldIndex.ExcelFile, 2147483647, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)ViewLevelFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ViewLevelFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("ViewLevelEntity", "LastModifiedUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ViewLevelFieldIndex.LastModifiedUtc, 0, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "Name", typeof(System.String), false, false, false, false,  (int)ViewLevelFieldIndex.Name, 200, 0, 0);
			this.AddElementFieldInfo("ViewLevelEntity", "ObjectStatus", typeof(System.Int32), false, false, false, false,  (int)ViewLevelFieldIndex.ObjectStatus, 0, 0, 10);
			this.AddElementFieldInfo("ViewLevelEntity", "Scale", typeof(Nullable<System.Single>), false, false, false, true,  (int)ViewLevelFieldIndex.Scale, 0, 0, 24);
			this.AddElementFieldInfo("ViewLevelEntity", "TransitionX", typeof(Nullable<System.Single>), false, false, false, true,  (int)ViewLevelFieldIndex.TransitionX, 0, 0, 24);
			this.AddElementFieldInfo("ViewLevelEntity", "TransitionY", typeof(Nullable<System.Single>), false, false, false, true,  (int)ViewLevelFieldIndex.TransitionY, 0, 0, 24);
			this.AddElementFieldInfo("ViewLevelEntity", "ViewId", typeof(System.Int32), false, true, false, false,  (int)ViewLevelFieldIndex.ViewId, 0, 0, 10);
		}
	}
}