//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ConTech.Data.HelperClasses;
using ConTech.Data.FactoryClasses;
using ConTech.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ConTech.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Project'.<br/><br/></summary>
	[Serializable]
	public partial class ProjectEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ProjectViewEntity> _projectViews;
		private UserEntity _user;
		private UserEntity _user1;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ProjectEntityStaticMetaData _staticMetaData = new ProjectEntityStaticMetaData();
		private static ProjectRelations _relationsFactory = new ProjectRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name ProjectViews</summary>
			public static readonly string ProjectViews = "ProjectViews";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProjectEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProjectEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProjectEntity", InheritanceHierarchyType.None, false, (int)ConTech.Data.EntityType.ProjectEntity, typeof(ProjectEntity), typeof(ProjectEntityFactory), false);
				AddNavigatorMetaData<ProjectEntity, EntityCollection<ProjectViewEntity>>("ProjectViews", a => a._projectViews, (a, b) => a._projectViews = b, a => a.ProjectViews, () => new ProjectRelations().ProjectViewEntityUsingProjectId, typeof(ProjectViewEntity), (int)ConTech.Data.EntityType.ProjectViewEntity);
				AddNavigatorMetaData<ProjectEntity, UserEntity>("User", "Projects", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, ConTech.Data.RelationClasses.StaticProjectRelations.UserEntityUsingCreatedByUserIdStatic, ()=>new ProjectRelations().UserEntityUsingCreatedByUserId, null, new int[] { (int)ProjectFieldIndex.CreatedByUserId }, null, true, (int)ConTech.Data.EntityType.UserEntity);
				AddNavigatorMetaData<ProjectEntity, UserEntity>("User1", "Projects1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, ConTech.Data.RelationClasses.StaticProjectRelations.UserEntityUsingLastModifiedByUserIdStatic, ()=>new ProjectRelations().UserEntityUsingLastModifiedByUserId, null, new int[] { (int)ProjectFieldIndex.LastModifiedByUserId }, null, true, (int)ConTech.Data.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProjectEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProjectEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProjectEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProjectEntity</param>
		public ProjectEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Project which data should be fetched into this Project object</param>
		public ProjectEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Project which data should be fetched into this Project object</param>
		/// <param name="validator">The custom validator object for this ProjectEntity</param>
		public ProjectEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProjectEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProjectView' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProjectViews() { return CreateRelationInfoForNavigator("ProjectViews"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProjectEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProjectRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProjectView' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProjectViews { get { return _staticMetaData.GetPrefetchPathElement("ProjectViews", CommonEntityBase.CreateEntityCollection<ProjectViewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The CreatedByUserId property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."CreatedByUserId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CreatedByUserId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ProjectFieldIndex.CreatedByUserId, false); }
			set	{ SetValue((int)ProjectFieldIndex.CreatedByUserId, value); }
		}

		/// <summary>The DateCreatedUtc property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."DateCreatedUtc".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime DateCreatedUtc
		{
			get { return (System.DateTime)GetValue((int)ProjectFieldIndex.DateCreatedUtc, true); }
			set	{ SetValue((int)ProjectFieldIndex.DateCreatedUtc, value); }
		}

		/// <summary>The Description property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 750.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)ProjectFieldIndex.Description, true); }
			set	{ SetValue((int)ProjectFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ProjectFieldIndex.Id, true); }
			set { SetValue((int)ProjectFieldIndex.Id, value); }		}

		/// <summary>The LastModifiedByUserId property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."LastModifiedByUserId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LastModifiedByUserId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ProjectFieldIndex.LastModifiedByUserId, false); }
			set	{ SetValue((int)ProjectFieldIndex.LastModifiedByUserId, value); }
		}

		/// <summary>The LastModifiedUtc property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."LastModifiedUtc".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LastModifiedUtc
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ProjectFieldIndex.LastModifiedUtc, false); }
			set	{ SetValue((int)ProjectFieldIndex.LastModifiedUtc, value); }
		}

		/// <summary>The Name property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProjectFieldIndex.Name, true); }
			set	{ SetValue((int)ProjectFieldIndex.Name, value); }
		}

		/// <summary>The ObjectStatus property of the Entity Project<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Project"."ObjectStatus".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ObjectStatus
		{
			get { return (System.Int32)GetValue((int)ProjectFieldIndex.ObjectStatus, true); }
			set	{ SetValue((int)ProjectFieldIndex.ObjectStatus, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ProjectViewEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProjectViewEntity))]
		public virtual EntityCollection<ProjectViewEntity> ProjectViews { get { return GetOrCreateEntityCollection<ProjectViewEntity, ProjectViewEntityFactory>("Project", true, false, ref _projectViews); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ConTech.Data
{
	public enum ProjectFieldIndex
	{
		///<summary>CreatedByUserId. </summary>
		CreatedByUserId,
		///<summary>DateCreatedUtc. </summary>
		DateCreatedUtc,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>LastModifiedByUserId. </summary>
		LastModifiedByUserId,
		///<summary>LastModifiedUtc. </summary>
		LastModifiedUtc,
		///<summary>Name. </summary>
		Name,
		///<summary>ObjectStatus. </summary>
		ObjectStatus,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ConTech.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Project. </summary>
	public partial class ProjectRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProjectEntity and ProjectViewEntity over the 1:n relation they have, using the relation between the fields: Project.Id - ProjectView.ProjectId</summary>
		public virtual IEntityRelation ProjectViewEntityUsingProjectId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProjectViews", true, new[] { ProjectFields.Id, ProjectViewFields.ProjectId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProjectEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Project.CreatedByUserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingCreatedByUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, ProjectFields.CreatedByUserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProjectEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Project.LastModifiedByUserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingLastModifiedByUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.Id, ProjectFields.LastModifiedByUserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProjectRelations
	{
		internal static readonly IEntityRelation ProjectViewEntityUsingProjectIdStatic = new ProjectRelations().ProjectViewEntityUsingProjectId;
		internal static readonly IEntityRelation UserEntityUsingCreatedByUserIdStatic = new ProjectRelations().UserEntityUsingCreatedByUserId;
		internal static readonly IEntityRelation UserEntityUsingLastModifiedByUserIdStatic = new ProjectRelations().UserEntityUsingLastModifiedByUserId;

		/// <summary>CTor</summary>
		static StaticProjectRelations() { }
	}
}
