//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using ConTech.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ConTech.Data.Read.Persistence
{

	/// <summary>Static class for (extension) methods for fetching and projecting instances of ConTech.Data.Read.DtoClasses.ProjectView from the entity model.</summary>
	public static partial class ProjectViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToProjectView(System.Linq.IQueryable{ConTech.Data.EntityClasses.ProjectEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToProjectView(ref System.Linq.Expressions.Expression<Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToProjectView(EntityQuery{ConTech.Data.EntityClasses.ProjectEntity}, ConTech.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToProjectView(EntityQuery{ConTech.Data.EntityClasses.ProjectEntity}, ConTech.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToProjectViewQs(ref System.Linq.Expressions.Expression<Func<ConTech.Data.Read.DtoClasses.ProjectView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static ProjectViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to ConTech.Data.Read.DtoClasses.ProjectView which instances are projected from the results of the specified baseQuery, which returns ConTech.Data.EntityClasses.ProjectEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve ConTech.Data.Read.DtoClasses.ProjectView instances</returns>
		public static IQueryable<ConTech.Data.Read.DtoClasses.ProjectView> ProjectToProjectView(this IQueryable<ConTech.Data.EntityClasses.ProjectEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to ConTech.Data.Read.DtoClasses.ProjectView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns ConTech.Data.EntityClasses.ProjectEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve ConTech.Data.Read.DtoClasses.ProjectView instances</returns>
		public static DynamicQuery<ConTech.Data.Read.DtoClasses.ProjectView> ProjectToProjectView(this EntityQuery<ConTech.Data.EntityClasses.ProjectEntity> baseQuery, ConTech.Data.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<ConTech.Data.Read.DtoClasses.ProjectView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToProjectViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new ConTech.Data.Read.DtoClasses.ProjectView()
				{
					CreatedByUserId = ProjectFields.CreatedByUserId.Source("__BQ").ToValue<Nullable<System.Int32>>(),
					DateCreatedUtc = ProjectFields.DateCreatedUtc.Source("__BQ").ToValue<System.DateTime>(),
					Description = ProjectFields.Description.Source("__BQ").ToValue<System.String>(),
					Id = ProjectFields.Id.Source("__BQ").ToValue<System.Int32>(),
					LastModifiedByUserId = ProjectFields.LastModifiedByUserId.Source("__BQ").ToValue<Nullable<System.Int32>>(),
					LastModifiedUtc = ProjectFields.LastModifiedUtc.Source("__BQ").ToValue<Nullable<System.DateTime>>(),
					Name = ProjectFields.Name.Source("__BQ").ToValue<System.String>(),
					ObjectStatus = ProjectFields.ObjectStatus.Source("__BQ").ToValue<System.Int32>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_ProjectView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to ConTech.Data.Read.DtoClasses.ProjectView which instances are projected from the ConTech.Data.EntityClasses.ProjectEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>ConTech.Data.EntityClasses.ProjectEntity instance created from the specified entity instance</returns>
		public static ConTech.Data.Read.DtoClasses.ProjectView ProjectToProjectView(this ConTech.Data.EntityClasses.ProjectEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView>> mainProjection = p__0 => new ConTech.Data.Read.DtoClasses.ProjectView()
			{
				CreatedByUserId = p__0.CreatedByUserId,
				DateCreatedUtc = p__0.DateCreatedUtc,
				Description = p__0.Description,
				Id = p__0.Id,
				LastModifiedByUserId = p__0.LastModifiedByUserId,
				LastModifiedUtc = p__0.LastModifiedUtc,
				Name = p__0.Name,
				ObjectStatus = p__0.ObjectStatus,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_ProjectView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<ConTech.Data.EntityClasses.ProjectEntity, ConTech.Data.Read.DtoClasses.ProjectView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToProjectView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


